server:
  port: 8084

spring:
  application:
    name: spring-test
  datasource: # ?????
    name: local_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: root
    username: root
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.reptile.entity


logging:
  level:
    com.example.reptile.mapper: debug